<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="inputName"
     targetNamespace="http://oracle.com/sca/soapservice/ApplicationBussinesRule/ProjectDirectTv/inputName"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:inp1="http://www.example.org"
     xmlns:tns="http://oracle.com/sca/soapservice/ApplicationBussinesRule/ProjectDirectTv/inputName"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.example.org" schemaLocation="xsd/prueba.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="input" element="inp1:exampleInput"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="output" element="inp1:exampleOutput"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
